// ========================================================================
//   This File Is Generated by hir-preprocessor.py ! Do Not Modify !
// ========================================================================

#define CBASE_HIR_INODE(__) \
__(Expr            ) \
__(ControlFlow     ) \
__(Test            ) \
__(SpecializeBinary) \
__(EffectNode      ) \
__(PhiNode         ) \
__(Merge           ) \
__(JumpWithValue   ) \
__(ReadEffect      ) \
__(WriteEffect     ) \
__(StaticRef       ) \
__(RefGet          ) \
__(EffectBarrier   ) \
__(RefSet          ) \
__(HardBarrier     ) \
__(SoftBarrier     ) \
__(DynamicBinary   ) \
__(EffectPhiBase   ) \
__(ObjectResize    ) \
__(ListResize      ) \

